import json, os
from pathlib import Path
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

BASE = Path(__file__).parent
with (BASE/'content'/'latest.json').open(encoding='utf-8') as f:
    data = json.load(f)

creds = Credentials(
    token=None,
    refresh_token=os.environ['YOUTUBE_REFRESH_TOKEN'],
    token_uri='https://oauth2.googleapis.com/token',
    client_id=os.environ['YOUTUBE_CLIENT_ID'],
    client_secret=os.environ['YOUTUBE_CLIENT_SECRET'],
    scopes=['https://www.googleapis.com/auth/youtube.upload'],
)

youtube = build('youtube','v3',credentials=creds)

parts = [data.get('description','').strip()]

# Credits are generated by the scheduled ChatGPT selector after verifying the asset license.
for key in ('background_credit', 'music_credit'):
    credit = data.get(key, '').strip()
    if credit:
        parts.append(credit)

hashtags = ' '.join(data.get('hashtags',[])).strip()
if hashtags:
    parts.append(hashtags)

description = '\n\n'.join(p for p in parts if p)[:5000]

body = {
  'snippet': {
    'title': data['title'][:100],
    'description': description,
    'categoryId': '23'
  },
  'status': {
    'privacyStatus': os.getenv('YOUTUBE_PRIVACY','private'),
    'selfDeclaredMadeForKids': False
  }
}

media = MediaFileUpload(str(BASE/'output'/'short.mp4'), mimetype='video/mp4', resumable=True)
request = youtube.videos().insert(part='snippet,status', body=body, media_body=media)
response = None
while response is None:
    _, response = request.next_chunk()
print('Uploaded video ID:', response['id'])
print('Background source:', data.get('background_source_url', 'not provided'))
print('Music:', data.get('music_title', 'selected track'), '-', data.get('music_artist', 'unknown artist'))
print('Music source:', data.get('music_source_url', 'not provided'))
