import json
import os
import re
from pathlib import Path

from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

from schedule_utils import scheduled_publish_at_from_selection

BASE = Path(__file__).parent
QUEUE_SELECTION = BASE / 'output' / 'queue_selection.json'
with (BASE / 'content' / 'latest.json').open(encoding='utf-8') as f:
    data = json.load(f)

creds = Credentials(
    token=None,
    refresh_token=os.environ['YOUTUBE_REFRESH_TOKEN'],
    token_uri='https://oauth2.googleapis.com/token',
    client_id=os.environ['YOUTUBE_CLIENT_ID'],
    client_secret=os.environ['YOUTUBE_CLIENT_SECRET'],
    scopes=[
        'https://www.googleapis.com/auth/youtube.upload',
        'https://www.googleapis.com/auth/youtube.readonly',
    ],
)

youtube = build('youtube', 'v3', credentials=creds, cache_discovery=False)

parts = [data.get('description', '').strip()]

# Credits are generated by the scheduled ChatGPT selector after verifying the asset license.
for key in ('background_credit', 'music_credit'):
    credit = data.get(key, '').strip()
    if credit:
        parts.append(credit)

# The planner may already include hashtags in description. Append only tags that are
# not already present so YouTube metadata remains clean instead of duplicating them.
base_description = '\n\n'.join(p for p in parts if p)
existing_tags = {tag.lower() for tag in re.findall(r'(?<!\w)#[A-Za-z0-9_]+', base_description)}
extra_tags = []
for tag in data.get('hashtags', []) or []:
    tag = str(tag).strip()
    if not tag:
        continue
    normalized = tag if tag.startswith('#') else f'#{tag}'
    if normalized.lower() not in existing_tags:
        extra_tags.append(normalized)
        existing_tags.add(normalized.lower())

if extra_tags:
    parts.append(' '.join(extra_tags))

description = '\n\n'.join(p for p in parts if p)[:5000]
title = data['title'][:100]

schedule_mode = os.getenv('YOUTUBE_SCHEDULED_UPLOAD', '').strip().lower() in {'1', 'true', 'yes'}
publish_at = None
if schedule_mode:
    publish_at = scheduled_publish_at_from_selection(QUEUE_SELECTION)


def find_existing_upload():
    """Return a recent exact-match upload so retries cannot create duplicates.

    This protects the failure window where YouTube accepted the prior upload but
    GitHub queue/archive state failed to persist. Exact title + exact generated
    description is intentionally strict so unrelated videos are not reused.
    """
    channels = youtube.channels().list(part='contentDetails', mine=True).execute()
    items = channels.get('items', []) or []
    if not items:
        return None
    uploads_playlist = (
        items[0].get('contentDetails', {})
        .get('relatedPlaylists', {})
        .get('uploads')
    )
    if not uploads_playlist:
        return None

    playlist = youtube.playlistItems().list(
        part='contentDetails',
        playlistId=uploads_playlist,
        maxResults=50,
    ).execute()
    video_ids = [
        item.get('contentDetails', {}).get('videoId')
        for item in playlist.get('items', []) or []
    ]
    video_ids = [video_id for video_id in video_ids if video_id]
    if not video_ids:
        return None

    videos = youtube.videos().list(
        part='snippet',
        id=','.join(video_ids),
        maxResults=50,
    ).execute()
    for item in videos.get('items', []) or []:
        snippet = item.get('snippet', {})
        if snippet.get('title', '') == title and snippet.get('description', '') == description:
            return item.get('id')
    return None


existing_video_id = find_existing_upload()
if existing_video_id:
    print('Duplicate-safe recovery: matching YouTube upload already exists; reusing it.')
    print('Uploaded video ID:', existing_video_id)
    if publish_at:
        print('Scheduled publish at:', publish_at)
    print('Background source:', data.get('background_source_url', 'not provided'))
    print('Music:', data.get('music_title', 'selected track'), '-', data.get('music_artist', 'unknown artist'))
    print('Music source:', data.get('music_source_url', 'not provided'))
    raise SystemExit(0)

status = {
    'privacyStatus': 'private' if schedule_mode else os.getenv('YOUTUBE_PRIVACY', 'private'),
    'selfDeclaredMadeForKids': False,
}
if publish_at:
    status['publishAt'] = publish_at

body = {
    'snippet': {
        'title': title,
        'description': description,
        'categoryId': '23',
    },
    'status': status,
}

media = MediaFileUpload(str(BASE / 'output' / 'short.mp4'), mimetype='video/mp4', resumable=True)
request = youtube.videos().insert(part='snippet,status', body=body, media_body=media)
response = None
while response is None:
    _, response = request.next_chunk()
print('Uploaded video ID:', response['id'])
if publish_at:
    print('Scheduled publish at:', publish_at)
print('Background source:', data.get('background_source_url', 'not provided'))
print('Music:', data.get('music_title', 'selected track'), '-', data.get('music_artist', 'unknown artist'))
print('Music source:', data.get('music_source_url', 'not provided'))
